import Link from "next/link";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen">
          <nav className="sticky top-0">
            <div className="flex gap-3 p-4 bg-gray-200">
              <Link href="/">Home</Link>
              <Link href="/entrar">Entrar</Link>
              <Link href="/cadastro">Cadastro</Link>
            </div>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
