name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Excluir arquivos sensíveis antes do deploy
      - name: Remove sensitive files
        run: |
          rm -f ansible/.vault_pass
          rm -f ansible/roles/postgres/vars/vault.yml      
      - name: Copy site via SSH with Password
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: ${{ secrets.PROJECT_PATH }}

  build:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install and build Next.js
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            bash scripts/deploy.sh
            #[ ! -f ansible/.vault_pass ] && echo "${{ secrets.VAULT_PASS }}" > ansible/.vault_pass
            #mkdir ./ansible/roles/postgres/vars/
            #cat > ansible/roles/postgres/vars/vault.yml << 'EOF'
            #${{ secrets.VAULT_YML_CONTENT }}
            #EOF
            # Ajustar permissões
            #chmod 600 ansible/.vault_pass
            #chmod 600 ansible/roles/postgres/vars/vault.yml
            #chmod 600 ansible/.vault_pass
            